import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class PlayerService {
  constructor() {}

  playerData = {
    status: 200,
    body: [
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'SAC',
        position: 'PG',
        field_goals_made: 5.4,
        field_goals_attempted: 24.8,
        two_pointers_made: 5.4,
        two_pointers_attempted: 10.5,
        three_pointers_made: 0.0,
        three_pointers_attempted: 14.3,
        offensive_rebounds: 0.0,
        defensive_rebounds: 2.7,
        rebounds: 2.7,
        assists: 6.3,
        steals: 2.7,
        turnovers: 4.5,
        points: 16.2,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'HOU',
        position: 'PG',
        field_goals_made: 8.2,
        field_goals_attempted: 24.8,
        two_pointers_made: 6.3,
        two_pointers_attempted: 15.2,
        three_pointers_made: 1.8,
        three_pointers_attempted: 9.1,
        offensive_rebounds: 0.0,
        defensive_rebounds: 9.1,
        rebounds: 9.1,
        assists: 2.7,
        steals: 0.9,
        turnovers: 0.9,
        points: 26.7,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'NO',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 10.5,
        two_pointers_made: 1.8,
        two_pointers_attempted: 2.7,
        three_pointers_made: 1.8,
        three_pointers_attempted: 7.3,
        offensive_rebounds: 0.0,
        defensive_rebounds: 2.7,
        rebounds: 2.7,
        assists: 2.7,
        steals: 0.0,
        turnovers: 3.6,
        points: 11.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'BOS',
        position: 'PG',
        field_goals_made: 10.5,
        field_goals_attempted: 21.9,
        two_pointers_made: 7.3,
        two_pointers_attempted: 13.3,
        three_pointers_made: 2.7,
        three_pointers_attempted: 8.2,
        offensive_rebounds: 0.9,
        defensive_rebounds: 1.8,
        rebounds: 2.7,
        assists: 8.2,
        steals: 0.9,
        turnovers: 3.6,
        points: 26.7,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'WAS',
        position: 'PG',
        field_goals_made: 7.3,
        field_goals_attempted: 19.0,
        two_pointers_made: 5.4,
        two_pointers_attempted: 13.3,
        three_pointers_made: 1.8,
        three_pointers_attempted: 5.4,
        offensive_rebounds: 1.8,
        defensive_rebounds: 5.4,
        rebounds: 7.3,
        assists: 7.3,
        steals: 0.0,
        turnovers: 0.9,
        points: 20.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'CHA',
        position: 'PG',
        field_goals_made: 4.5,
        field_goals_attempted: 12.4,
        two_pointers_made: 3.6,
        two_pointers_attempted: 8.2,
        three_pointers_made: 0.9,
        three_pointers_attempted: 3.6,
        offensive_rebounds: 0.0,
        defensive_rebounds: 1.8,
        rebounds: 1.8,
        assists: 2.7,
        steals: 1.8,
        turnovers: 1.8,
        points: 11.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'ORL',
        position: 'PG',
        field_goals_made: 7.3,
        field_goals_attempted: 16.2,
        two_pointers_made: 3.6,
        two_pointers_attempted: 8.2,
        three_pointers_made: 3.6,
        three_pointers_attempted: 7.3,
        offensive_rebounds: 0.0,
        defensive_rebounds: 4.5,
        rebounds: 4.5,
        assists: 4.5,
        steals: 2.7,
        turnovers: 0.9,
        points: 24.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MIA',
        position: 'PG',
        field_goals_made: 4.5,
        field_goals_attempted: 18.1,
        two_pointers_made: 3.6,
        two_pointers_attempted: 11.4,
        three_pointers_made: 0.9,
        three_pointers_attempted: 6.3,
        offensive_rebounds: 1.8,
        defensive_rebounds: 6.3,
        rebounds: 8.2,
        assists: 1.8,
        steals: 0.0,
        turnovers: 4.5,
        points: 11.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'ATL',
        position: 'PG',
        field_goals_made: 12.4,
        field_goals_attempted: 21.9,
        two_pointers_made: 7.3,
        two_pointers_attempted: 11.4,
        three_pointers_made: 4.5,
        three_pointers_attempted: 10.5,
        offensive_rebounds: 0.9,
        defensive_rebounds: 3.6,
        rebounds: 4.5,
        assists: 8.2,
        steals: 1.8,
        turnovers: 3.6,
        points: 29.5,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'HOU',
        position: 'PG',
        field_goals_made: 10.5,
        field_goals_attempted: 20.0,
        two_pointers_made: 8.2,
        two_pointers_attempted: 11.4,
        three_pointers_made: 1.8,
        three_pointers_attempted: 8.2,
        offensive_rebounds: 0.9,
        defensive_rebounds: 9.1,
        rebounds: 10.5,
        assists: 4.5,
        steals: 0.9,
        turnovers: 2.7,
        points: 26.7,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'DEN',
        position: 'PG',
        field_goals_made: 4.5,
        field_goals_attempted: 18.1,
        two_pointers_made: 3.6,
        two_pointers_attempted: 12.4,
        three_pointers_made: 0.9,
        three_pointers_attempted: 5.4,
        offensive_rebounds: 0.0,
        defensive_rebounds: 2.7,
        rebounds: 2.7,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.9,
        points: 13.3,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'LAC',
        position: 'PG',
        field_goals_made: 6.3,
        field_goals_attempted: 15.2,
        two_pointers_made: 4.5,
        two_pointers_attempted: 9.1,
        three_pointers_made: 1.8,
        three_pointers_attempted: 5.4,
        offensive_rebounds: 0.9,
        defensive_rebounds: 2.7,
        rebounds: 3.6,
        assists: 1.8,
        steals: 1.8,
        turnovers: 0.9,
        points: 16.2,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'LAC',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 11.4,
        two_pointers_made: 1.8,
        two_pointers_attempted: 4.5,
        three_pointers_made: 1.8,
        three_pointers_attempted: 6.3,
        offensive_rebounds: 0.9,
        defensive_rebounds: 1.8,
        rebounds: 2.7,
        assists: 5.4,
        steals: 0.0,
        turnovers: 1.8,
        points: 11.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'CHI',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 6.3,
        two_pointers_made: 2.7,
        two_pointers_attempted: 4.5,
        three_pointers_made: 0.9,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.9,
        defensive_rebounds: 4.5,
        rebounds: 5.4,
        assists: 0.0,
        steals: 2.7,
        turnovers: 3.6,
        points: 10.5,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'NO',
        position: 'PG',
        field_goals_made: 9.1,
        field_goals_attempted: 19.0,
        two_pointers_made: 5.4,
        two_pointers_attempted: 11.4,
        three_pointers_made: 3.6,
        three_pointers_attempted: 7.3,
        offensive_rebounds: 1.8,
        defensive_rebounds: 2.7,
        rebounds: 4.5,
        assists: 5.4,
        steals: 0.0,
        turnovers: 4.5,
        points: 26.7,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'NY',
        position: 'PG',
        field_goals_made: 5.4,
        field_goals_attempted: 19.0,
        two_pointers_made: 3.6,
        two_pointers_attempted: 10.5,
        three_pointers_made: 1.8,
        three_pointers_attempted: 8.2,
        offensive_rebounds: 0.0,
        defensive_rebounds: 1.8,
        rebounds: 1.8,
        assists: 1.8,
        steals: 3.6,
        turnovers: 4.5,
        points: 15.2,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'ATL',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 7.3,
        two_pointers_made: 1.8,
        two_pointers_attempted: 4.5,
        three_pointers_made: 1.8,
        three_pointers_attempted: 2.7,
        offensive_rebounds: 0.9,
        defensive_rebounds: 3.6,
        rebounds: 4.5,
        assists: 1.8,
        steals: 0.0,
        turnovers: 0.9,
        points: 11.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'BOS',
        position: 'PG',
        field_goals_made: 1.8,
        field_goals_attempted: 5.4,
        two_pointers_made: 0.0,
        two_pointers_attempted: 1.8,
        three_pointers_made: 1.8,
        three_pointers_attempted: 3.6,
        offensive_rebounds: 0.0,
        defensive_rebounds: 1.8,
        rebounds: 1.8,
        assists: 3.6,
        steals: 0.0,
        turnovers: 0.9,
        points: 7.3,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'TOR',
        position: 'PG',
        field_goals_made: 8.2,
        field_goals_attempted: 15.2,
        two_pointers_made: 3.6,
        two_pointers_attempted: 7.3,
        three_pointers_made: 4.5,
        three_pointers_attempted: 7.3,
        offensive_rebounds: 1.8,
        defensive_rebounds: 4.5,
        rebounds: 6.3,
        assists: 3.6,
        steals: 0.0,
        turnovers: 1.8,
        points: 23.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'HOU',
        position: 'PG',
        field_goals_made: 9.1,
        field_goals_attempted: 25.7,
        two_pointers_made: 5.4,
        two_pointers_attempted: 16.2,
        three_pointers_made: 3.6,
        three_pointers_attempted: 9.1,
        offensive_rebounds: 0.9,
        defensive_rebounds: 6.3,
        rebounds: 7.3,
        assists: 4.5,
        steals: 0.9,
        turnovers: 1.8,
        points: 28.6,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'OKC',
        position: 'PG',
        field_goals_made: 4.5,
        field_goals_attempted: 12.4,
        two_pointers_made: 2.7,
        two_pointers_attempted: 6.3,
        three_pointers_made: 1.8,
        three_pointers_attempted: 5.4,
        offensive_rebounds: 0.9,
        defensive_rebounds: 3.6,
        rebounds: 4.5,
        assists: 4.5,
        steals: 0.0,
        turnovers: 0.9,
        points: 12.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MIN',
        position: 'PG',
        field_goals_made: 6.3,
        field_goals_attempted: 19.0,
        two_pointers_made: 5.4,
        two_pointers_attempted: 13.3,
        three_pointers_made: 0.9,
        three_pointers_attempted: 5.4,
        offensive_rebounds: 2.7,
        defensive_rebounds: 3.6,
        rebounds: 6.3,
        assists: 3.6,
        steals: 0.0,
        turnovers: 0.9,
        points: 17.1,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MEM',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 7.3,
        two_pointers_made: 3.6,
        two_pointers_attempted: 5.4,
        three_pointers_made: 0.0,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 1.8,
        defensive_rebounds: 0.9,
        rebounds: 2.7,
        assists: 0.0,
        steals: 0.9,
        turnovers: 2.7,
        points: 9.1,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MEM',
        position: 'PG',
        field_goals_made: 7.3,
        field_goals_attempted: 14.3,
        two_pointers_made: 4.5,
        two_pointers_attempted: 9.1,
        three_pointers_made: 2.7,
        three_pointers_attempted: 4.5,
        offensive_rebounds: 1.8,
        defensive_rebounds: 4.5,
        rebounds: 6.3,
        assists: 2.7,
        steals: 0.9,
        turnovers: 0.9,
        points: 18.1,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MIA',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 1.8,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.0,
        three_pointers_made: 0.0,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'CHA',
        position: 'PG',
        field_goals_made: 2.7,
        field_goals_attempted: 5.4,
        two_pointers_made: 1.8,
        two_pointers_attempted: 3.6,
        three_pointers_made: 0.9,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 3.6,
        defensive_rebounds: 1.8,
        rebounds: 5.4,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 6.3,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'DEN',
        position: 'PG',
        field_goals_made: 4.5,
        field_goals_attempted: 8.2,
        two_pointers_made: 3.6,
        two_pointers_attempted: 5.4,
        three_pointers_made: 0.9,
        three_pointers_attempted: 2.7,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.9,
        rebounds: 0.9,
        assists: 2.7,
        steals: 0.0,
        turnovers: 0.0,
        points: 13.3,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MIN',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 3.6,
        two_pointers_made: 0.9,
        two_pointers_attempted: 3.6,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 1.8,
        rebounds: 1.8,
        assists: 0.0,
        steals: 1.8,
        turnovers: 0.9,
        points: 3.6,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'MIN',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 7.3,
        two_pointers_made: 2.7,
        two_pointers_attempted: 5.4,
        three_pointers_made: 0.9,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.9,
        defensive_rebounds: 3.6,
        rebounds: 4.5,
        assists: 2.7,
        steals: 0.9,
        turnovers: 3.6,
        points: 15.2,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'POR',
        opponent: 'NO',
        position: 'PG',
        field_goals_made: 4.5,
        field_goals_attempted: 13.3,
        two_pointers_made: 3.6,
        two_pointers_attempted: 8.2,
        three_pointers_made: 0.9,
        three_pointers_attempted: 4.5,
        offensive_rebounds: 0.0,
        defensive_rebounds: 2.7,
        rebounds: 2.7,
        assists: 2.7,
        steals: 0.0,
        turnovers: 1.8,
        points: 11.4,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'MEM',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 3.6,
        two_pointers_made: 0.0,
        two_pointers_attempted: 1.8,
        three_pointers_made: 0.0,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.9,
        rebounds: 0.9,
        assists: 1.8,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'LAL',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.0,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.0,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.9,
        rebounds: 0.9,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.0,
        points: 1.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'LAC',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 3.6,
        two_pointers_made: 0.9,
        two_pointers_attempted: 1.8,
        three_pointers_made: 0.0,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 2.7,
        steals: 0.0,
        turnovers: 0.9,
        points: 1.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'MIA',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 1.8,
        steals: 0.9,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'SA',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 1.8,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 0.9,
        defensive_rebounds: 0.9,
        rebounds: 1.8,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.9,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'MIL',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 4.5,
        two_pointers_made: 0.0,
        two_pointers_attempted: 2.7,
        three_pointers_made: 0.9,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.9,
        rebounds: 0.9,
        assists: 2.7,
        steals: 1.8,
        turnovers: 0.0,
        points: 3.6,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'IND',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.0,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.0,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.9,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'IND',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.0,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.0,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'UTA',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 1.8,
        two_pointers_made: 0.9,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.9,
        rebounds: 0.9,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.0,
        points: 4.5,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'SA',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 1.8,
        two_pointers_made: 0.0,
        two_pointers_attempted: 1.8,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.9,
        defensive_rebounds: 2.7,
        rebounds: 3.6,
        assists: 0.9,
        steals: 0.0,
        turnovers: 1.8,
        points: 3.6,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'TOR',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.9,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.9,
        points: 1.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'LAC',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.9,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.0,
        points: 1.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'ORL',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 1.8,
        two_pointers_made: 0.9,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 1.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'NY',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.0,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.0,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'IND',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.9,
        defensive_rebounds: 2.7,
        rebounds: 3.6,
        assists: 0.9,
        steals: 0.0,
        turnovers: 2.7,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'PHI',
        position: 'PG',
        field_goals_made: 1.8,
        field_goals_attempted: 3.6,
        two_pointers_made: 1.8,
        two_pointers_attempted: 2.7,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 2.7,
        defensive_rebounds: 1.8,
        rebounds: 4.5,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.0,
        points: 3.6,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'CHI',
        position: 'PG',
        field_goals_made: 1.8,
        field_goals_attempted: 2.7,
        two_pointers_made: 0.9,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.9,
        three_pointers_attempted: 1.8,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 4.5,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'ATL',
        position: 'PG',
        field_goals_made: 2.7,
        field_goals_attempted: 4.5,
        two_pointers_made: 2.7,
        two_pointers_attempted: 3.6,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 1.8,
        defensive_rebounds: 2.7,
        rebounds: 4.5,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.9,
        points: 7.3,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'ORL',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'PHI',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 3.6,
        two_pointers_made: 0.9,
        two_pointers_attempted: 2.7,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 0.9,
        defensive_rebounds: 3.6,
        rebounds: 4.5,
        assists: 0.0,
        steals: 0.9,
        turnovers: 0.0,
        points: 1.8,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'TOR',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.0,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 0.0,
        defensive_rebounds: 0.0,
        rebounds: 0.0,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'BKN',
        position: 'PG',
        field_goals_made: 0.0,
        field_goals_attempted: 0.9,
        two_pointers_made: 0.0,
        two_pointers_attempted: 0.9,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.9,
        defensive_rebounds: 0.0,
        rebounds: 0.9,
        assists: 0.0,
        steals: 0.0,
        turnovers: 0.0,
        points: 0.0,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'IND',
        position: 'PG',
        field_goals_made: 3.6,
        field_goals_attempted: 3.6,
        two_pointers_made: 3.6,
        two_pointers_attempted: 3.6,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.0,
        offensive_rebounds: 0.0,
        defensive_rebounds: 2.7,
        rebounds: 2.7,
        assists: 0.9,
        steals: 0.9,
        turnovers: 0.0,
        points: 10.5,
      },
      {
        player_id: 20002712,
        name: 'Dalano Banton',
        season: 2024,
        team: 'BOS',
        opponent: 'WAS',
        position: 'PG',
        field_goals_made: 0.9,
        field_goals_attempted: 2.7,
        two_pointers_made: 0.9,
        two_pointers_attempted: 1.8,
        three_pointers_made: 0.0,
        three_pointers_attempted: 0.9,
        offensive_rebounds: 1.8,
        defensive_rebounds: 0.0,
        rebounds: 1.8,
        assists: 0.9,
        steals: 0.0,
        turnovers: 0.9,
        points: 1.8,
      },
    ],
  };

  getPlayers = (numberOfPlayers: number) => {
    return this.playerData.body.slice(0, numberOfPlayers);
  };

  applyFilterByPlayerStats = (
    statsOf: string,
    numberOfGame: number,
    lineVal: number
  ) => {
    let players = this.getPlayers(numberOfGame);
    const graphData = this.prepareGraphData(players, statsOf, lineVal);
    return { players, graphData };
  };

  prepareGraphData = (players: any[], statsOf: string, lineVal: number) => {
    const labels = players.map((player) => player.opponent);
    const statsKeys = this.getStatsKeyByStatsId(statsOf);
    const baseValue = lineVal;
    const playerData = players.map((player) => {
      const stats = statsKeys.reduce((acc: any, key) => {
        acc[key] = player[key];
        return acc;
      }, {});

      const totalValue = statsKeys.reduce((sum, key) => sum + player[key], 0);

      const color =
        totalValue > baseValue ? 'rgba(16, 185, 129, 1)' : 'rgba(255, 0, 0, 1)';

      return { Stats: stats, color, total: totalValue };
    });

    const lineDataSets = {
      type: 'line',
      label: 'Dataset 1',
      borderColor: 'purple',
      borderWidth: 2,
      fill: false,
      tension: 1,
      data: playerData.map((item: any) => baseValue),
    };

    return {
      labels,
      datasets: [lineDataSets, ...this.createDataSet(playerData)],
    };
  };
  createDataSet = (data: any) => {
    const statKeys = Object.keys(data[0].Stats);
    const baseOpacity = 1;

    return statKeys.map((statKey, index) => {
      const currentOpacity = baseOpacity - index * 0.3;

      return {
        type: 'bar',
        label: statKey,
        backgroundColor: data.map((item: any) =>
          item.color.replace(
            /rgba\((\d+), (\d+), (\d+), 1\)/,
            `rgba($1, $2, $3, ${currentOpacity.toFixed(2)})`
          )
        ),
        borderColor: data.map((item: any) =>
          item.color.replace(
            /rgba\((\d+), (\d+), (\d+), 1\)/,
            `rgba($1, $2, $3, ${currentOpacity.toFixed(2)})`
          )
        ),
        borderRadius: 10,
        data: data.map((item: any) => item.Stats[statKey]),
      };
    });
  };

  getStatsKeyByStatsId(statsId: string) {
    switch (statsId) {
      case 'PTS':
        return ['points'];
      case 'TO':
        return ['turnovers'];
      case 'STLS':
        return ['steals'];
      case 'ASTS':
        return ['assists'];
      case 'REBS':
        return ['rebounds'];
      case 'D-REB':
        return ['defensive_rebounds'];
      case 'O-REB':
        return ['offensive_rebounds'];
      case '3PM':
        return ['three_pointers_made'];
      case '2PA':
        return ['two_pointers_made'];
      case 'PA':
        return ['points', 'assists'];
      case 'PR':
        return ['points', 'rebounds'];
      case 'RA':
        return ['rebounds', 'assists'];
      case 'PRA':
        return ['points', 'rebounds', 'assists'];
      default:
        return [];
    }
  }

  getStatsList() {
    return [
      {
        id: 'PTS',
        name: 'Points',
      },
      {
        id: 'TO',
        name: 'Turnovers',
      },
      {
        id: 'STLS',
        name: 'Steals',
      },
      {
        id: 'ASTS',
        name: 'Assists',
      },
      {
        id: 'REBS',
        name: 'Rebounds',
      },
      {
        id: 'D-REB',
        name: 'Defensive Rebounds',
      },
      {
        id: 'O-REB',
        name: 'Offensive Rebounds',
      },
      {
        id: '3PM',
        name: 'Three Pointers Made',
      },
      {
        id: '2PA',
        name: 'Two Pointers Made',
      },
      {
        id: 'PA',
        name: 'Points & Assists',
      },
      {
        id: 'PR',
        name: 'Points & Rebounds',
      },
      {
        id: 'RA',
        name: 'Rebounds & Assists',
      },
      {
        id: 'PRA',
        name: 'Points, Rebounds & Assists',
      },
    ];
  }

  preparePlayerProfile() {
    const player = this.playerData.body;

    const playerStats: any = player.reduce(
      (acc, player) => {
        acc.points += player.points;
        acc.rebounds += player.rebounds;
        acc.assists += player.assists;
        acc.steals += player.steals;
        acc.turnovers += player.turnovers;
        acc.field_goals_made += player.field_goals_made;
        acc.field_goals_attempted += player.field_goals_attempted;
        acc.two_pointers_made += player.two_pointers_made;
        acc.two_pointers_attempted += player.two_pointers_attempted;
        acc.three_pointers_made += player.three_pointers_made;
        acc.three_pointers_attempted += player.three_pointers_attempted;
        acc.offensive_rebounds += player.offensive_rebounds;
        acc.defensive_rebounds += player.defensive_rebounds;
        return acc;
      },
      {
        points: 0,
        rebounds: 0,
        assists: 0,
        steals: 0,
        turnovers: 0,
        field_goals_made: 0,
        field_goals_attempted: 0,
        two_pointers_made: 0,
        two_pointers_attempted: 0,
        three_pointers_made: 0,
        three_pointers_attempted: 0,
        offensive_rebounds: 0,
        defensive_rebounds: 0,
      }
    );

    for (const key in playerStats) {
      if (playerStats.hasOwnProperty(key)) {
        playerStats[key as keyof typeof playerProfile] = parseFloat(
          playerStats[key as keyof typeof playerProfile].toFixed(1)
        );
      }
    }

    let play = player[0];
    const playerProfile = {
      ...playerStats,
      player_id: play.player_id,
      name: play.name,
      season: play.season,
      team: play.team,
      position: play.position,
      totalMatches: player.length,
    };
    return playerProfile;
  }
}
